// api/login.js
import jwt from "jsonwebtoken";

export default function handler(req, res) {
  // 1. Guard Clause: Ensure Vercel parsed the JSON body
  if (!req.body || !req.body.password) {
    return res.status(400).json({
      success: false,
      error: "Payload missing or invalid Content-Type",
    });
  }

  const { username } = req.body;

 const incomingHash = req.body.password?.trim().toLowerCase();
 const storedHash = process.env.AUTH_PASS?.trim();

 // Compare Boolean without logging the strings
 const isMatch = incomingHash === storedHash;
 console.log("DOES IT MATCH? ->", isMatch);

  /**
   * 2. Environment Variables (Injected by DotenvX)
   * AUTH_PASS: Now the 64-character SHA-256 hash string.
   * JWT_SECRET: The secret key used to sign your session token.
   */
  const storedUser = process.env.AUTH_USER?.trim();
  // const storedHash = process.env.AUTH_PASS?.trim(); // Use .trim() to remove hidden spaces
  const jwtSecret = process.env.JWT_SECRET;

  // --- DEBUG START ---
  console.log("--- 2025 Backend Comparison ---");
  console.log(`Incoming User: [${username}]`);
  console.log(`Stored User:   [${storedUser}]`);
  console.log(
    `Incoming Hash: [${incomingHash}] (Len: ${incomingHash?.length})`
  );
  console.log(`Stored Hash:   [${storedHash}] (Len: ${storedHash?.length})`);
  console.log(
    "Match Result:",
    username === storedUser && incomingHash === storedHash
  );
  console.log("---------------------------------");
  // --- DEBUG END ---
  // 3. Security Handshake
  // We compare the SHA-256 hash generated by the browser to the one in our vault.
  if (username === storedUser && incomingHash === storedHash) {
    /**
     * 4. Generate JWT
     * We sign a token to prove the user is logged in.
     * In 2025, 2 hours is the standard duration for an SPA session.
     */
    const token = jwt.sign({ user: username }, jwtSecret, { expiresIn: "2h" });

    // 5. Success Response
    return res.status(200).json({
      success: true,
      token,
    });
  } else {
    // 6. Unauthorized Response
    return res.status(401).json({
      success: false,
      message: "Invalid credentials",
    });
  }
}
